include:
  - project: 'kangsiwoo/ci-templates'
    file: 'node.yml'
    ref: main

variables:
  IMAGE: $REGISTRY/kangsiwoo/project-bot-web

test:
  extends: .test-node
  before_script:
    - npm ci
  script:
    - npm run lint || true
    - npm run build

build:
  extends: .build

deploy-dev:
  extends: .deploy-dev

deploy-staging:
  extends: .deploy-staging

deploy-prod:
  extends: .deploy-prod
